#! /usr/bin/perl

my @dirs, @temps, $type='crc', $digest_mode;
my $DEBUG = 0;

sub usage {
	print STDERR "Usage: $0 [--checksum=TYPE] [DIR1 DIR2 ...]\n", "TYPE: crc (default), md5, both"; 
	exit -1; 
}

sub print_duplicate { print "$_[0] $_[1]\n" }

END { 
	foreach (@temps) {
		unlink $_;
		if(-f $_) { print 'cannot remove '.$_ }
	}
}

foreach (@ARGV) {
	/^--checksum=(\S+)$/ and $type = $1 and next;
	/^--digest$/ and $digest_mode = 1 and next;

	-d $_ && push(@dirs, $_) or die "Invalid directory: $_";
}

if(!$digest_mode) {
	if($#dirs>=0) {
		use File::Temp qw(tempfile);
		foreach my $dir (@dirs) {
			my ($fh, $fname) = tempfile();
			open(IN,  "/bin/ls -1 $dir | tail -n+2 |");
			open(OUT, "> $fname") or die 'Cannot write to temporary files.';
			print OUT "$dir/$_" while(<IN>);
			push(@temps, $fname);
		}
		open(IN, 'cat '.join(' ', @temps)." | $0 --checksum=$type --digest | sort -k 1,1 |"); 
	}
	while(1) {
		$_ = <IN> or last;
		/^ *(\S+) +(\S+)/ or die "Invalid entry: $_";

		!$file1 and ($hash1, $file1) = ($1, $2) and next;		

		($hash2, $file2) = ($1, $2);

		$is_duplicate = ($hash1 eq $hash2 and (stat($file1))[1] != (stat($file2))[1]);

		$DEBUG and print($is_duplicate ? 'o' : 'x', ' ', $file1.':'.$hash1.' '.$file2.':'.$hash2, "\n") and $is_duplicate and next;

		$is_duplicate and print_duplicate($file1, $file2) and next;
		
		($hash1, $file1) = ($hash2, $file2);
	}
	exit;
}

use String::CRC32;
use Digest::MD5;
$ctx = Digest::MD5->new;

$mode = 0;
$type eq 'crc'  and $mode = 1;
$type eq 'md5'  and $mode = 2;
$type eq 'both' and $mode = 3;
$mode or die "Invalid digest type: $type";

sub digest {
	open(FILE, $_[0]) or die "Cannot open file $_[0]";
	binmode FILE;

	if($mode&1) { $crc = crc32(*FILE) }
	if($mode&3) { seek FILE, 0, 0 } 
	if($mode&2) { $ctx->addfile(*FILE); $md5 = $ctx->hexdigest } 
	
	if($mode==3) { return $md5.'-'.$crc }
	if($mode==2) { return $md5 }
	if($mode==1) { return $crc }
}

chomp and (-f $_ && -s $_) and print (&digest($_), ' ', $_, "\n") while(<STDIN>);
