#! /usr/bin/perl

my @dirs, @lists, @temps, $digest_mode, $verbose_mode, $hash_type = 'crc';

use constant false => 0;
use constant true  => 1;

sub usage {
	print STDERR "Usage: $0 [OPTION]... {DIR,FILE}*\nOptions:\n", 
	"\t--checksum=TYPE\t Specify the type of checksum. TYPE can be {crc, md5, both}. Default is crc.\n",
	"\t--digest\t Don't find duplicates. Instead, print the checksums of the input files.\n",
	"\t--parallel=N\t Change the number of sorts run concurrently to N\n",
	"\t--verbose\t Print debug messages.\n",
	"\t--help\t Print this message\n"
	;
	exit -1; 
}

sub print_duplicate { print "$_[0] $_[1]\n" }

END { 
	foreach (@temps) {
		unlink $_;
		if(-f $_) { print 'cannot remove '.$_ }
	}
}

foreach (@ARGV) {
	/^--checksum=(\S+)$/  and $hash_type = $1 and next;
	/^--parallel=(\d+)$/  and $parellel = $1 and next;
	/^--digest$/          and $digest_mode = true and next;
	/^--verbose$/         and $verbose_mode = true and next;
	/^--help$/            and &usage;
	-d $_ and push(@dirs, $_) and next;
	-f $_ and push(@lists, $_) and next;
	die "Invalid argument: $_";
}

if(@dirs or @lists) {
	use File::Temp qw(tempfile);
	foreach my $dir (@dirs) {
		my ($fh, $fname) = tempfile();
		open(IN,  "/bin/ls -1 $dir | tail -n+2 |");
		open(OUT, "> $fname") or die 'Cannot write to temporary files.';
		print OUT "$dir/$_" while(<IN>);
		push(@temps, $fname);
	}
}

if(!$digest_mode) {

	if(@dirs or @lists) {
		open(IN, 'cat '.join(' ', @temps).' '.join(' ', @lists)." | $0 --checksum=$hash_type --digest | sort -k 1,1 |"); 
	}
	else {
		open(IN, "cat | sort -k 1,1 |");
	}

	while(1) {
		$_ = <IN> or last;
		/^ *(\S+) +(\S+)/ or die "Invalid entry: $_";

		!$file1 and ($hash1, $file1) = ($1, $2) and next;		

		($hash2, $file2) = ($1, $2);

		$is_duplicate = ($hash1 eq $hash2 and (stat($file1))[1] != (stat($file2))[1]);

		$verbose_mode and print($is_duplicate ? 'o' : 'x', ' ', $file1.':'.$hash1.' '.$file2.':'.$hash2, "\n") and $is_duplicate and next;

		$is_duplicate and &print_duplicate($file1, $file2) and next;
		
		($hash1, $file1) = ($hash2, $file2);
	}
	exit;
}

use String::CRC32;
use Digest::MD5;
$ctx = Digest::MD5->new;

$mode = 0;
$hash_type eq 'crc'  and $mode = 1;
$hash_type eq 'md5'  and $mode = 2;
$hash_type eq 'both' and $mode = 3;
$mode or die "Invalid digest type: $hash_type";

sub digest {
	open(FILE, $_[0]) or die "Cannot open file $_[0]";
	binmode FILE;

	if($mode&1) { $crc = crc32(*FILE) }
	if($mode&3) { seek FILE, 0, 0 } 
	if($mode&2) { $ctx->addfile(*FILE); $md5 = $ctx->hexdigest } 
	
	if($mode==3) { return $md5.'-'.$crc }
	if($mode==2) { return $md5 }
	if($mode==1) { return $crc }
}

if(@dirs or @lists) {
	open(IN, 'cat '.join(' ', @temps).' '.join(' ', @lists)." |"); 
}
else {
	*IN = *STDIN;
}
chomp and (-f $_ && -s $_) and print (&digest($_), ' ', $_, "\n") while(<IN>);
